# Generated by Django 3.1.4 on 2023-04-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file_emails/', verbose_name='Файл с email-ами')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки файла')),
            ],
        ),
        migrations.CreateModel(
            name='EmailResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_valid', models.BooleanField(verbose_name="Правильность email'a")),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validate_email.emailfile')),
            ],
        ),
    ]
